//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maths_quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public int Score { get; set; }
        public System.DateTime Date { get; set; }
        public int LevelId { get; set; }
        public int ProfileId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
